// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OWT6BA_HFT_2022232.Repository.Database;

namespace OWT6BA_HFT_2022232.Repository.Database.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20231203130859_BookDbSeeds")]
    partial class BookDbSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorName = "Adam Grant"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorName = "Barack Obama"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorName = "Ben Lynch"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorName = "Bill Gates"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorName = "Carl Zimmer"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorName = "Charles Darwin"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorName = "Charles Dikens"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorName = "Dean Koontz"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorName = "Franz Kafka"
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorName = "George Orwell"
                        },
                        new
                        {
                            AuthorId = 11,
                            AuthorName = "George R.R. Martin"
                        },
                        new
                        {
                            AuthorId = 12,
                            AuthorName = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorId = 13,
                            AuthorName = "Julia Quinn"
                        },
                        new
                        {
                            AuthorId = 14,
                            AuthorName = "Nelson Mandela"
                        },
                        new
                        {
                            AuthorId = 15,
                            AuthorName = "Oscar Wilde"
                        },
                        new
                        {
                            AuthorId = 16,
                            AuthorName = "Robert T Kiyosaki"
                        },
                        new
                        {
                            AuthorId = 17,
                            AuthorName = "Terry O'Brien"
                        },
                        new
                        {
                            AuthorId = 18,
                            AuthorName = "Tim Marshall"
                        });
                });

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfReviews")
                        .HasColumnType("int");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 10,
                            CategoryId = 11,
                            NumberOfReviews = 61318,
                            Pages = 328,
                            Price = 79.0,
                            Rating = 4.5,
                            ReleaseYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 17,
                            CategoryId = 7,
                            NumberOfReviews = 578,
                            Pages = 600,
                            Price = 203.30000000000001,
                            Rating = 4.2999999999999998,
                            ReleaseYear = 2015,
                            Title = "50 Greatest Short Stories"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 11,
                            CategoryId = 1,
                            NumberOfReviews = 11191,
                            Pages = 761,
                            Price = 369.0,
                            Rating = 4.5,
                            ReleaseYear = 1998,
                            Title = "A Clash of Kings"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 11,
                            CategoryId = 1,
                            NumberOfReviews = 2188,
                            Pages = 694,
                            Price = 449.0,
                            Rating = 4.5,
                            ReleaseYear = 1996,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 2,
                            CategoryId = 9,
                            NumberOfReviews = 1217,
                            Pages = 768,
                            Price = 184.0,
                            Rating = 4.7000000000000002,
                            ReleaseYear = 2020,
                            Title = "A Promised Land"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 7,
                            CategoryId = 5,
                            NumberOfReviews = 4721,
                            Pages = 304,
                            Price = 159.0,
                            Rating = 4.5,
                            ReleaseYear = 1859,
                            Title = "A Tale of Two Cities"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 13,
                            CategoryId = 5,
                            NumberOfReviews = 17090,
                            Pages = 358,
                            Price = 294.04000000000002,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2001,
                            Title = "An Offer From a Gentleman: Bridgerton"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 10,
                            CategoryId = 7,
                            NumberOfReviews = 33951,
                            Pages = 112,
                            Price = 99.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 13,
                            CategoryId = 1,
                            NumberOfReviews = 30616,
                            Pages = 339,
                            Price = 399.0,
                            Rating = 4.5,
                            ReleaseYear = 2000,
                            Title = "Bridgerton: The Duke and I"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 3,
                            CategoryId = 4,
                            NumberOfReviews = 15367,
                            Pages = 384,
                            Price = 414.0,
                            Rating = 4.7000000000000002,
                            ReleaseYear = 2018,
                            Title = "Dirty Genes: A Breakthrough Program to Treat the Root Cause of Illness and Optimize Your Health"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 12,
                            CategoryId = 2,
                            NumberOfReviews = 5772,
                            Pages = 78,
                            Price = 391.0,
                            Rating = 4.5,
                            ReleaseYear = 2001,
                            Title = "Fantastic Beasts and Where to Find Them"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 12,
                            CategoryId = 1,
                            NumberOfReviews = 31243,
                            Pages = 251,
                            Price = 299.0,
                            Rating = 4.7000000000000002,
                            ReleaseYear = 1998,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 12,
                            CategoryId = 7,
                            NumberOfReviews = 38252,
                            Pages = 223,
                            Price = 285.94999999999999,
                            Rating = 4.7000000000000002,
                            ReleaseYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 12,
                            CategoryId = 1,
                            NumberOfReviews = 24040,
                            Pages = 317,
                            Price = 158.65000000000001,
                            Rating = 4.7000000000000002,
                            ReleaseYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 4,
                            CategoryId = 3,
                            NumberOfReviews = 7474,
                            Pages = 272,
                            Price = 749.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2021,
                            Title = "How to Avoid a Climate Disaster: The Solutions We Have and the Breakthroughs We Need"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 8,
                            CategoryId = 12,
                            NumberOfReviews = 1853,
                            Pages = 480,
                            Price = 324.32999999999998,
                            Rating = 4.4000000000000004,
                            ReleaseYear = 1996,
                            Title = "Intensity: A powerful thriller of violence and terror"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 14,
                            CategoryId = 9,
                            NumberOfReviews = 3821,
                            Pages = 630,
                            Price = 456.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 1994,
                            Title = "Long Walk To Freedom"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 9,
                            CategoryId = 7,
                            NumberOfReviews = 6279,
                            Pages = 217,
                            Price = 79.0,
                            Rating = 4.5,
                            ReleaseYear = 1915,
                            Title = "Metamorphosis"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 18,
                            CategoryId = 9,
                            NumberOfReviews = 6854,
                            Pages = 320,
                            Price = 479.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2015,
                            Title = "Prisoners of Geography: Ten Maps That Tell You Everything You Need To Know About Global Politics"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 16,
                            CategoryId = 4,
                            NumberOfReviews = 3351,
                            Pages = 336,
                            Price = 291.0,
                            Rating = 4.5,
                            ReleaseYear = 1997,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 5,
                            CategoryId = 4,
                            NumberOfReviews = 421,
                            Pages = 672,
                            Price = 133.94999999999999,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2018,
                            Title = "She Has Her Mother's Laugh: The Powers, Perversions, and Potential of Heredity"
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 6,
                            CategoryId = 6,
                            NumberOfReviews = 5414,
                            Pages = 502,
                            Price = 159.0,
                            Rating = 4.5,
                            ReleaseYear = 1859,
                            Title = "The Origin of Species"
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 15,
                            CategoryId = 7,
                            NumberOfReviews = 5763,
                            Pages = 272,
                            Price = 259.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 1890,
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 18,
                            CategoryId = 8,
                            NumberOfReviews = 1272,
                            Pages = 380,
                            Price = 381.99000000000001,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2021,
                            Title = "The Power of Geography: Ten Maps that Reveal the Future of Our World – the sequel to Prisoners of Geography"
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 12,
                            CategoryId = 11,
                            NumberOfReviews = 7692,
                            Pages = 128,
                            Price = 199.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2008,
                            Title = "The Tales of Beedle the Bard: A Harry Potter Hogwarts Library Book"
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 13,
                            CategoryId = 10,
                            NumberOfReviews = 24030,
                            Pages = 354,
                            Price = 257.33999999999997,
                            Rating = 4.5,
                            ReleaseYear = 2000,
                            Title = "The Viscount Who Loved Me: Bridgerton"
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 1,
                            CategoryId = 11,
                            NumberOfReviews = 6762,
                            Pages = 320,
                            Price = 505.0,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2021,
                            Title = "Think Again: The Power of Knowing What You Don't Know"
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 13,
                            CategoryId = 5,
                            NumberOfReviews = 12991,
                            Pages = 368,
                            Price = 257.33999999999997,
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2004,
                            Title = "When He Was Wicked: Bridgerton"
                        });
                });

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action & Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Film & Photography"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Internet & Digital Media"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Historical Fiction"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "History"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Literature & Fiction"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Maps & Atlases"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Politics"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Society & Social Sciences"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Travel"
                        });
                });

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Book", b =>
                {
                    b.HasOne("OWT6BA_HFT_2022232.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OWT6BA_HFT_2022232.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OWT6BA_HFT_2022232.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
